import { NextResponse } from "next/server";

const reviews = [
  // PROPERTY 1
  {
    id: 1,
    propertyId: "1",
    author: "John",
    date: "March 2026",
    rating: 5,
    text: "Amazing stay! The apartment was clean and exactly like the photos.",
  },
  {
    id: 2,
    propertyId: "1",
    author: "Albert",
    date: "February 2026",
    rating: 4,
    text: "Great location and nice host. Would stay again.",
  },
  {
    id: 3,
    propertyId: "1",
    author: "Emma",
    date: "January 2026",
    rating: 5,
    text: "Super cozy place, felt like home!",
  },
  {
    id: 4,
    propertyId: "1",
    author: "David",
    date: "December 2025",
    rating: 4,
    text: "Nice view and comfortable bed.",
  },
  {
    id: 5,
    propertyId: "1",
    author: "Sophia",
    date: "November 2025",
    rating: 5,
    text: "Perfect stay, everything was amazing.",
  },

  // PROPERTY 2
  {
    id: 6,
    propertyId: "2",
    author: "Pele",
    date: "March 2026",
    rating: 4,
    text: "Very good experience, especially the location.",
  },
  {
    id: 7,
    propertyId: "2",
    author: "Lucas",
    date: "February 2026",
    rating: 5,
    text: "Loved everything about this place!",
  },
  {
    id: 8,
    propertyId: "2",
    author: "Olivia",
    date: "January 2026",
    rating: 4,
    text: "Clean and modern, would recommend.",
  },
  {
    id: 9,
    propertyId: "2",
    author: "Noah",
    date: "December 2025",
    rating: 5,
    text: "Amazing host and great communication.",
  },
  {
    id: 10,
    propertyId: "2",
    author: "Liam",
    date: "November 2025",
    rating: 4,
    text: "Good stay overall.",
  },

  // PROPERTY 3
  {
    id: 11,
    propertyId: "3",
    author: "Mia",
    date: "March 2026",
    rating: 5,
    text: "Beautiful apartment with stunning view!",
  },
  {
    id: 12,
    propertyId: "3",
    author: "Ethan",
    date: "February 2026",
    rating: 4,
    text: "Nice place, very clean.",
  },
  {
    id: 13,
    propertyId: "3",
    author: "Ava",
    date: "January 2026",
    rating: 5,
    text: "Highly recommended!",
  },
  {
    id: 14,
    propertyId: "3",
    author: "James",
    date: "December 2025",
    rating: 4,
    text: "Comfortable and well located.",
  },
  {
    id: 15,
    propertyId: "3",
    author: "Isabella",
    date: "November 2025",
    rating: 5,
    text: "Fantastic stay, will come again.",
  },

  {
    id: 16,
    propertyId: "4",
    author: "Daniel",
    date: "March 2026",
    rating: 5,
    text: "Fantastic apartment! Everything was clean and well organized.",
  },
  {
    id: 17,
    propertyId: "4",
    author: "Anna",
    date: "February 2026",
    rating: 4,
    text: "Very comfortable stay, great location near city center.",
  },
  {
    id: 18,
    propertyId: "4",
    author: "Michael",
    date: "January 2026",
    rating: 5,
    text: "Loved the interior design and cozy atmosphere.",
  },
  {
    id: 19,
    propertyId: "4",
    author: "Sara",
    date: "December 2025",
    rating: 4,
    text: "Nice place, everything worked perfectly.",
  },
  {
    id: 20,
    propertyId: "4",
    author: "Chris",
    date: "November 2025",
    rating: 5,
    text: "Highly recommend! Great host and smooth check-in.",
  },

  {
    id: 21,
    propertyId: "5",
    author: "Lucas",
    date: "March 2026",
    rating: 5,
    text: "Amazing place with a beautiful view!",
  },
  {
    id: 22,
    propertyId: "5",
    author: "Emma",
    date: "February 2026",
    rating: 4,
    text: "Very clean and modern apartment.",
  },
  {
    id: 23,
    propertyId: "5",
    author: "Oliver",
    date: "January 2026",
    rating: 5,
    text: "Perfect for a weekend getaway.",
  },
  {
    id: 24,
    propertyId: "5",
    author: "Sophia",
    date: "December 2025",
    rating: 5,
    text: "Loved everything about this stay!",
  },
  {
    id: 25,
    propertyId: "5",
    author: "Jack",
    date: "November 2025",
    rating: 4,
    text: "Nice location and friendly host.",
  },

  {
    id: 26,
    propertyId: "6",
    author: "Ethan",
    date: "March 2026",
    rating: 4,
    text: "Good experience overall, everything was as expected.",
  },
  {
    id: 27,
    propertyId: "6",
    author: "Mia",
    date: "February 2026",
    rating: 5,
    text: "Super clean and well equipped apartment.",
  },
  {
    id: 28,
    propertyId: "6",
    author: "Noah",
    date: "January 2026",
    rating: 4,
    text: "Comfortable stay, would come back again.",
  },
  {
    id: 29,
    propertyId: "6",
    author: "Ava",
    date: "December 2025",
    rating: 5,
    text: "Everything was perfect, great host!",
  },
  {
    id: 30,
    propertyId: "6",
    author: "James",
    date: "November 2025",
    rating: 4,
    text: "Nice place and good communication.",
  },

  {
    id: 31,
    propertyId: "7",
    author: "Isabella",
    date: "March 2026",
    rating: 5,
    text: "Beautiful apartment with a great vibe.",
  },
  {
    id: 32,
    propertyId: "7",
    author: "William",
    date: "February 2026",
    rating: 4,
    text: "Good location and very clean.",
  },
  {
    id: 33,
    propertyId: "7",
    author: "Charlotte",
    date: "January 2026",
    rating: 5,
    text: "Loved the design and comfort.",
  },
  {
    id: 34,
    propertyId: "7",
    author: "Benjamin",
    date: "December 2025",
    rating: 4,
    text: "Nice stay, everything was smooth.",
  },
  {
    id: 35,
    propertyId: "7",
    author: "Amelia",
    date: "November 2025",
    rating: 5,
    text: "Highly recommended for short trips!",
  },

  {
    id: 36,
    propertyId: "8",
    author: "Logan",
    date: "March 2026",
    rating: 5,
    text: "Excellent place, very comfortable and clean.",
  },
  {
    id: 37,
    propertyId: "8",
    author: "Ella",
    date: "February 2026",
    rating: 4,
    text: "Nice apartment, good location.",
  },
  {
    id: 38,
    propertyId: "8",
    author: "Henry",
    date: "January 2026",
    rating: 5,
    text: "Amazing experience, everything was perfect.",
  },
  {
    id: 39,
    propertyId: "8",
    author: "Grace",
    date: "December 2025",
    rating: 4,
    text: "Comfortable and clean place.",
  },
  {
    id: 40,
    propertyId: "8",
    author: "Alexander",
    date: "November 2025",
    rating: 5,
    text: "Great host and beautiful apartment.",
  },
];

export async function GET(req: Request) {
  const { searchParams } = new URL(req.url);
  const propertyId = searchParams.get("propertyId");

  const filtered = propertyId
    ? reviews.filter((r) => r.propertyId === propertyId)
    : reviews;

  return NextResponse.json(filtered);
}
